name: haseela
description: A Flutter app for child tasks and rewards.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.1.0
  # Optional (add if you plan to use auth later)
  # firebase_auth: ^4.5.0

  # UI & utility packages
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.5
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
